#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.18
#  in conjunction with Tcl version 8.6
#    Oct 30, 2018 02:41:43 AM IST  platform: Windows NT

import sys
print("hello")
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import search_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    search_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    search_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None
def find_result(query):
    print(query)



class Toplevel1:
    def getTextInput(self):
        input = self.Text1.get("1.0", 'end-1c')
        find_result(input)

    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font9 = "-family Verdana -size 9 -weight normal -slant roman "  \
            "-underline 0 -overstrike 0"

        top.geometry("600x450+552+240")
        top.title("Search Engine")
        top.configure(background="#d8612d")

        self.Text1 = tk.Text(top)
        self.Text1.place(relx=0.233, rely=0.489, relheight=0.098, relwidth=0.507)

        self.Text1.configure(background="white")
        self.Text1.configure(font="TkTextFont")
        self.Text1.configure(foreground="black")
        self.Text1.configure(highlightbackground="#d9d9d9")
        self.Text1.configure(highlightcolor="black")
        self.Text1.configure(insertbackground="black")
        self.Text1.configure(selectbackground="#c4c4c4")
        self.Text1.configure(selectforeground="black")
        self.Text1.configure(width=304)
        self.Text1.configure(wrap='word')

        self.Labelframe1 = tk.LabelFrame(top)
        self.Labelframe1.place(relx=0.183, rely=0.178, relheight=0.122
                , relwidth=0.65)
        self.Labelframe1.configure(relief='groove')
        self.Labelframe1.configure(foreground="black")
        self.Labelframe1.configure(text='''Welcome To Music Match''')
        self.Labelframe1.configure(background="#5466d8")
        self.Labelframe1.configure(width=390)

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.4, rely=0.622, height=33, width=86)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#ff944d")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Search''')
        self.Button1.configure(width=86)
        self.Button1.configure(command=self.getTextInput)


        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.217, rely=0.356, height=26, width=353)
        self.Label1.configure(background="#d8612d")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Enter Your Query Here''')
        self.Label1.configure(width=353)

if __name__ == '__main__':
    vp_start_gui()





